blueprint:
  name: Doorbell Notification
  description: 'This automation blueprint creates a camera snapshot when the doorbell
    is activated and sends a notification to your phone with the picture.
    '
  domain: automation
  input:
    binary_sensor:
      name: Doorbell State
      description: Entity representing a doorbell press or state change.
      selector:
        entity:
          domain: binary_sensor
    camera:
      name: Camera
      description: The camera which creates the snapshot
      selector:
        entity:
          domain: camera
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive
        notifications
      selector:
        device:
          integration: mobile_app
    is_ios:
      name: iOS or Android?
      description: true = iOS, false = Android
      selector:
        boolean: {}
      default: true
    notification_title:
      name: Notification Title
      description: 'Default: "Ding Dong"'
      default: Ding Dong
    notification_message:
      name: Notification message
      description: 'Default: "{{ binary_sensor_name }} was pressed"'
      default: '{{ binary_sensor_name }} was pressed'
    click_action:
      name: Tap to view dashboard
      description: 'Path to camera dashboard'
      default: '/overview'
    delay_start:
      name: Delay (Optional)
      description: Wait before creating camera snapshot
      default: 0.0
      selector:
        number:
          min: 0.0
          max: 60.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    mode:
      name: Mode
      description: The mode of the automation
      selector:
        select:
          options:
            - single
            - restart
            - queued
            - parallel
          mode: dropdown
      default: single
    throttle_time:
      name: Throttle time (Optional)
      description: Time to wait before the automation can trigger again
      default: 0.0
      selector:
        number:
          min: 0.0
          max: 300.0
          unit_of_measurement: seconds
          mode: slider
          step: 5.0
  source_url: https://community.home-assistant.io/t/send-camera-snapshot-when-doorbell-was-activated/123456
trigger:
  platform: state
  entity_id: !input 'binary_sensor'
  from: 'off'
  to: 'on'
variables:
  binary_sensor: !input 'binary_sensor'
  binary_sensor_name: '{{ states[binary_sensor].name }}'
  camera: !input 'camera'
  notify_device: !input 'notify_device'
  is_ios: !input 'is_ios'
  notification_title: !input 'notification_title'
  notification_message: !input 'notification_message'
  click_action: !input 'click_action'
  delay_start: !input 'delay_start'
  throttle_time: !input 'throttle_time'
  snapshot_create_file_path: /config/www/tmp/snapshot_{{ states[camera].object_id
    }}.jpg
  snapshot_access_file_path: '{{ snapshot_create_file_path | replace(''/config/www'',''/local'')
    }}'
mode: !input 'mode'
action:
- delay: '{{ delay_start }}'
- service: camera.snapshot
  entity_id: !input 'camera'
  data:
    filename: '{{ snapshot_create_file_path }}'
- device_id: !input 'notify_device'
  domain: mobile_app
  type: notify
  title: '{{ notification_title }}'
  message: '{{ notification_message }}'
  data: 
    attachment:
        url: '{{ snapshot_access_file_path }}'
        content_type: 'JPEG'
    url: '{{ click_action }}'
- delay: '{{ throttle_time }}'
